services:
  - type: web
    name: wordle-backend
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:10000
    autoDeploy: true